<?php
/**
 * Created by PhpStorm.
 * User: glen9
 * Date: 2018/9/4
 * Time: 11:59
 */

namespace app\admin\controller\riskcontrol;
use app\common\controller\Backend;

class Monthly extends Backend
{
    /**
     * @var null
     */
    protected $model = null;

    /**
     *
     */
    public  function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \think\response\Json|void
     */
    public function index()
    {
        $this->loadlang('order/salesorder');
        return $this->view->fetch();
    }

    /**
     * 新车月供管理
     * @return string
     * @throws \think\Exception
     */
    public function newcarMonthly(){
        $this->model = new \app\admin\model\NewcarMonthly;
        $this->view->assign("monthlyDataList", $this->model->getMonthlyDataList());


        return $this->view->fetch();

    }
}