<?php
/**
 * Created by PhpStorm.
 * User: glen9
 * Date: 2018/10/22
 * Time: 10:09
 */

namespace app\admin\model;

use think\Model;

class BigData extends Model
{
    protected $name = 'big_data';

    public function initialize()
    {
//        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 关联大数据，跟新审批结果 字段
     * @return \think\model\relation\BelongsTo
     */
    public function bigdata()
    {
        return $this->belongsTo('SalesOrder', 'sales_order_id','id')->setEagerlyType(1);
    }

}